/** Two-tier narration engine.
 *
 *   Tier 1 — pre-generated ElevenLabs MP3 at /demo-audio/step-NN.mp3
 *            Higher production quality, deterministic timing, works
 *            offline once cached. Generated by
 *            scripts/generate_demo_audio.py with Adam (pNInz6obpgDQGcFmaJgB)
 *            at the boutique-brand voice settings.
 *
 *   Tier 2 — Web Speech API fallback (browser TTS). Used when the MP3
 *            request 404s, the user is offline, or the browser blocks
 *            <audio> autoplay before any user interaction.
 *
 * Calling code does:  await narration.speak({ stepId, text, onEnd })
 * and gets the best available voice for that step automatically.
 */

interface SpeakOptions {
  stepId?: number          // 1..12 → /demo-audio/step-01.mp3
  text:    string          // narration text (used by both tiers)
  onEnd?:  () => void
}

export class NarrationEngine {
  private audio: HTMLAudioElement | null = null

  async speak({ stepId, text, onEnd }: SpeakOptions): Promise<void> {
    this.cancel()

    // Tier 1: try the pre-generated MP3
    if (stepId !== undefined) {
      const url = `/demo-audio/step-${String(stepId).padStart(2, '0')}.mp3`
      const played = await this._tryAudio(url, onEnd)
      if (played) return
    }

    // Tier 2: fall back to Web Speech API
    this._speakWithBrowser(text, onEnd)
  }

  /** Returns true if the audio started playing successfully. */
  private _tryAudio(url: string, onEnd?: () => void): Promise<boolean> {
    return new Promise(resolve => {
      const a = new Audio(url)
      a.preload = 'auto'
      a.onended = () => { onEnd?.() }
      a.onerror = () => resolve(false)
      a.oncanplay = () => {
        // canplay fires before play() — try playing now
        const p = a.play()
        if (p && typeof p.then === 'function') {
          p.then(() => { this.audio = a; resolve(true) })
           .catch(() => resolve(false))
        } else {
          this.audio = a
          resolve(true)
        }
      }
      // Hard fallback if neither canplay nor error fires within 4s
      setTimeout(() => resolve(false), 4000)
    })
  }

  private _speakWithBrowser(text: string, onEnd?: () => void): void {
    if (!('speechSynthesis' in window)) { onEnd?.(); return }
    window.speechSynthesis.cancel()

    const start = () => {
      const voices = window.speechSynthesis.getVoices()
      const preferred =
           voices.find(v => v.name === 'Samantha')
        || voices.find(v => v.name === 'Google US English')
        || voices.find(v => v.lang === 'en-US' && v.localService)
        || voices.find(v => v.lang.startsWith('en'))
      const utt = new SpeechSynthesisUtterance(text)
      if (preferred) utt.voice = preferred
      utt.rate = 0.93; utt.pitch = 1.0; utt.volume = 0.9
      utt.onend   = () => onEnd?.()
      utt.onerror = () => onEnd?.()
      window.speechSynthesis.speak(utt)
    }
    if (window.speechSynthesis.getVoices().length === 0) {
      window.speechSynthesis.onvoiceschanged = () => {
        window.speechSynthesis.onvoiceschanged = null
        start()
      }
      setTimeout(start, 600)   // safety fallback
    } else {
      start()
    }
  }

  cancel(): void {
    if (this.audio) {
      this.audio.pause()
      this.audio.currentTime = 0
      this.audio.src = ''
      this.audio = null
    }
    if ('speechSynthesis' in window) window.speechSynthesis.cancel()
  }

  pause(): void {
    this.audio?.pause()
    if ('speechSynthesis' in window) window.speechSynthesis.pause()
  }

  resume(): void {
    this.audio?.play().catch(() => {})
    if ('speechSynthesis' in window) window.speechSynthesis.resume()
  }
}
